### ISSUE TITLE
Restaurant API

### ISSUE THREAD

**Issue by danielkim13** [danielkim13/code_breakers_repo#8]
Story recap: As a user, I should be able to select a city and it provides available parking places.

Acceptance Criteria

GIVEN a CityGirl dropdown menu on the left column
WHEN I select a city
THEN the webpage displays 5 nearby restaurants with minimum business name, and business address. Additional information can be added for the potential customer. 

Server-side API used: Yelp

**Comment by trwilhite** [comment]
Updated to reflect new API used - Open Brewery DB API
